# Generated by Django 4.2.2 on 2023-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('Цвет', models.CharField(help_text='Цветовое обозначение тэга', max_length=50, unique=True, verbose_name='Цвет')),
                ('Слаг', models.SlugField(max_length=250, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
