# Generated by Django 4.2.2 on 2023-06-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
