# Generated by Django 4.2.2 on 2023-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_ingredientrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Ингредиенты',
            field=models.ManyToManyField(help_text='Продукты для приготовления блюда по рецепту', related_name='recipes', through='contents.IngredientRecipe', to='contents.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Тэг',
            field=models.ManyToManyField(help_text='Укажите, к какому типу относится блюдо', related_name='recipes', through='contents.TagRecipe', to='contents.tag', verbose_name='Тэг'),
        ),
    ]

    replaces = [
        ('contents', '0009_recipe_ингредиенты_recipe_тэг'),
    ]
