# Generated by Django 4.2.2 on 2023-06-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_alter_tagrecipe_options_recipe_дата_публикации'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Название',
            new_name='name',
        ),
    ]
