# Generated by Django 4.2.2 on 2023-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_alter_favorites_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='ingredient_amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
