# Generated by Django 4.2.2 on 2023-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0024_alter_ingredientrecipe_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название блюда'),
        ),
    ]
