# Generated by Django 4.2.2 on 2023-06-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='fan',
            new_name='user',
        ),
    ]
