# Generated by Django 4.2.2 on 2023-06-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0029_alter_shoppingcart_recipe_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
