# Generated by Django 4.2.2 on 2023-06-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_в_подписках_user_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
